name: Build and deploy package

on:
  push:
    branches:
      -main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest 
    
    steps:
    - uses: actions/checkout@main

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'      
